### ISSUE TITLE
H2 Database Console

### ISSUE THREAD

**Issue by jukabarros** [Rudge/kotlin-javalin-realworld-example-app#5]
Hi, I would like to know how to enable the h2 db console? 
In spring projects, We just have to put these properties:
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

How about javalin project?
Thanks in advanced.

ps.: I dont know if it is the right place to send this question.

**Comment by Rudge** [comment]
Hi, thank you for the feedback.

I didn't configure the h2 console. So I changed the strategy of project to start the h2 console on [start application](https://github.com/Rudge/kotlin-javalin-realworld-example-app/blob/1ebb1bffd5e04a29026cadf7738c5c3ae9d9e08a/src/main/kotlin/io/realworld/app/App.kt#L7) and I updated the [README](https://github.com/Rudge/kotlin-javalin-realworld-example-app/blob/master/README.md#start-the-server)
